import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../lib/registry';
import { Container, GlobalStyles } from '../styles/global';
import Navbar from './navbar/navbar';
import Scene from './scene/scene';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ja1z?',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <GlobalStyles />
        <link rel="icon" href="/icon.png" />
        <body className={inter.className}>
          <Navbar />
          <Container>
            <Scene />
            {children}
          </Container>
        </body>
      </StyledComponentsRegistry>
    </html>
  )
}
